name: "Update the google apis"

on: push # for testing
# on:
#   # Create the PR once a week at 12:00 on Monday.
#   schedule:
#     - cron: '0 12 * * MON'
permissions:
   contents: read
   contents: write
   pull-requests: write

jobs:
  create-update-google-apis-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get current date
        run: echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - name: Run the `renovate.sh` script
        run: ./scripts/run.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with: 
          push-to-fork: alevenberg/skills-hello-github-actions
      - name: Verify everything compiles with Bazel
        run: cd sample && bazel build all
      - name: Verify everything compiles with CMake
        run: cd sample && cmake -S . -B build && cmake --build build

      # - name: Run the `renovate.sh` script
      #   run: ./external/googleapis/renovate.sh
      # - name: Verify everything compiles with Bazel
      #   run: bazel build //google/cloud/...
      # - name: Verify everything compiles with CMake
      #   run: ci/cloudbuild/build.sh -t cmake-install-pr
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     commit-message: chore(googleapis-sha): update the sha circa ${{ steps.date.outputs.date }}
      #     title: 'chore(googleapis-sha): update the sha circa ${{ steps.date.outputs.date }}'
      #     body: >
      #       This PR is auto-generated by 
      #       [updated-googleapis-sha](https://github.com/googleapis/google-cloud-cpp/.github/workflows/update-googleapis-sha).
      #     labels: dependencies